### ISSUE TITLE
Adapt tests to Exasol 2025.1.8

### ISSUE THREAD

**Issue by kaklakariada** [exasol/virtual-schema-common-document#193]
Integration tests with Exasol 8.32.0 fail with the following error, see https://github.com/exasol/virtual-schema-common-document/actions/runs/11897697309/job/33152523756?pr=192
```
Error:  Errors: 
Error:    DocumentAdapterIT.testEmptyQueryPlan:242->assertVirtualSchemaQueryWithEmptyQueryPlan:275->assertVirtualSchemaQuery:281->assertQueryResult:371 IllegalState Failed to run query 'SELECT my_timestamp FROM MY_VIRTUAL_SCHEMA.BOOKS': Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 1 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT * FROM (VALUES (CAST(NULL AS  TIMESTAMP))) WHERE FALSE) (Session: 1816082074585661440)
Error:    DocumentAdapterIT.testToTimestampMapping:232->assertVirtualSchemaQuery:270->assertVirtualSchemaQuery:281->assertQueryResult:371 IllegalState Failed to run query 'SELECT MY_TIMESTAMP FROM MY_VIRTUAL_SCHEMA.BOOKS;': Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 1 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT "MY_TIMESTAMP" FROM (SELECT "ADAPTER".IMPORT_FROM_FIXED_DATA_ADAPTER("DATA_LOADER", 'rO0ABX...) (Session: 1816082074585661440)
```

```
java.lang.IllegalStateException: Failed to run query 'SELECT MY_TIMESTAMP FROM MY_VIRTUAL_SCHEMA.BOOKS;': Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 1 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT "MY_TIMESTAMP" FROM (SELECT "ADAPTER".IMPORT_FROM_FIXED_DATA_ADAPTER("DATA_LOADER", 'rO0ABXNyADhjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5TY2hlbWFNYXBwaW5nUmVxdWVzdOio6FDZAiEzAgACTAAHY29sdW1uc3QAEExqYXZhL3V0aWwvTGlzdDtMABFwYXRoSW5SZW1vdGVUYWJsZXQAQUxjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZG9jdW1lbnRwYXRoL0RvY3VtZW50UGF0aEV4cHJlc3Npb247eHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyAERjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5Qcm9wZXJ0eVRvVGltZXN0YW1wQ29sdW1uTWFwcGluZyBuLRd0eJ4wAgACSQAQc2Vjb25kc1ByZWNpc2lvbkwAFW5vdFRpbWVzdGFtcEJlaGF2aW91cnQAQ0xjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZWRtbC9Db252ZXJ0YWJsZU1hcHBpbmdFcnJvckJlaGF2aW91cjt4cgBDY29tLmV4YXNvbC5hZGFwdGVyLmRvY3VtZW50Lm1hcHBpbmcuQWJzdHJhY3RQcm9wZXJ0eVRvQ29sdW1uTWFwcGluZ7jc0iZ0wnbKAgACTAATbG9va3VwRmFpbEJlaGF2aW91cnQAOExjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZWRtbC9NYXBwaW5nRXJyb3JCZWhhdmlvdXI7TAAUcGF0aFRvU291cmNlUHJvcGVydHlxAH4AAnhyADljb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5BYnN0cmFj...) (Session: 1816082074585661440)
	at com.exasol.adapter.document.DocumentAdapterIT.assertQueryResult(DocumentAdapterIT.java:371)
	at com.exasol.adapter.document.DocumentAdapterIT.assertVirtualSchemaQuery(DocumentAdapterIT.java:281)
	at com.exasol.adapter.document.DocumentAdapterIT.assertVirtualSchemaQuery(DocumentAdapterIT.java:270)
	at com.exasol.adapter.document.DocumentAdapterIT.testToTimestampMapping(DocumentAdapterIT.java:232)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

```
 Error:  com.exasol.adapter.document.DocumentAdapterIT.testEmptyQueryPlan(Fields, String)[1] -- Time elapsed: 2.311 s <<< ERROR!
java.lang.IllegalStateException: Failed to run query 'SELECT my_timestamp FROM MY_VIRTUAL_SCHEMA.BOOKS': Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 1 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT * FROM (VALUES (CAST(NULL AS  TIMESTAMP))) WHERE FALSE) (Session: 1816082074585661440)
	at com.exasol.adapter.document.DocumentAdapterIT.assertQueryResult(DocumentAdapterIT.java:371)
	at com.exasol.adapter.document.DocumentAdapterIT.assertVirtualSchemaQuery(DocumentAdapterIT.java:281)
	at com.exasol.adapter.document.DocumentAdapterIT.assertVirtualSchemaQueryWithEmptyQueryPlan(DocumentAdapterIT.java:275)
	at com.exasol.adapter.document.DocumentAdapterIT.testEmptyQueryPlan(DocumentAdapterIT.java:242)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
See also
* #186 
* #187 
* #188

**Comment by skyglass** [comment]
Fixed in this PR: https://github.com/exasol/virtual-schema-common-document/pull/209/files
